dept/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("home.urls")),
    path('jobs/', include("jobs.urls")),
    path('profile/', include("profiles.urls")),
    path('subscribe/', include("subscriptions.urls")),
    path('bookings/', include("bookings.urls")),
    path("social/", include("social.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import (DepListView, JobListView, delete_job, post_job,
                    register_interest, get_interested_members,
                    confirm_job_offer, EditJobView, delete_job, remove_offer)

"""
Job URLs
----------------

URL Routing for the Jobs App
"""


urlpatterns = [
    path('find_a_dep', DepListView.as_view(), name="dep_list"),
    path('find_a_job', JobListView.as_view(), name="job_list"),
    path("post_job", post_job, name="post_job"),
    path("edit_job/<int:job_id>", EditJobView.as_view(), name="edit_job"),
    path("delete_job/<int:job_id>", delete_job, name="delete_job"),
    path("register_interest/<int:job_id>/<str:username>",
         register_interest, name="register_interest"),
    path("remove_offer/<int:job_id>/<str:username>",
         remove_offer, name="remove_offer"),
    path("get_interested_members/<int:job_id>",
         get_interested_members, name="get_interested_members"),
    path("confirm_job_offer/<int:job_id>/<str:confirmed_user_username>",
         confirm_job_offer, name="confirm_job_offer")
]

jobs/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django_countries.fields import CountryField

from profiles.models import UserProfile, Instrument

import uuid


class JobQuerySet(models.QuerySet):
    """
    Customize queryset filtering to allow
    for URL parameters to be dynamically added.
    """

    def filter_by_params(self, filter_params, min_fee, max_fee):
        if not min_fee and not max_fee:
            return self.filter(**filter_params).exclude(
                is_taken=True).order_by("-id")
        else:
            return self.filter(
                **filter_params,
                fee__range=(min_fee, max_fee)).exclude(is_taken=True)


class JobManager(models.Manager):
    """
    Override default Django queryset manager,
    to allow for custom filter parameters.
    """

    def get_queryset(self):
        return JobQuerySet(self.model, using=self._db)

    def filter_queryset(self, filter_params, min_fee, max_fee):
        if not min_fee and not max_fee:
            return self.get_queryset().filter_by_params(
                 filter_params).order_by("-id")
        else:
            return self.get_queryset().filter_by_params(
                filter_params, min_fee, max_fee)


class Job(models.Model):
    """
    Model representing an instance of a job.

    Attributes:

        Job Number (CharField) - A UUID string representing a Job Instance.

        Job Poster (FK) - The member posting the job advertisement.

        Interested Member (FK) - The member registering interest in doing job.(

        Event Name (CharField) - The name of the event taking place.

        Artist Name (CharField) - The name of the artist who the job is for.

        Job Description (TextField) - A description of what the job entails.

        Fee (DecimalField) - The fee for the job.

        Event City (CharField) - The city where the event is taking place.

        Event Country (CountryField) - The country where the
                                       event is taking place.

        Event DateTime (DateTimeField) - THe date and time of the event.

        Interest Count (IntegerField) - An incremental field representing
                                        the amount of interest the
                                        job has received.

        Is Taken (Boolean) - Represents whether a dep has
                             been confirmed to play the job.
    """

    job_number = models.CharField(max_length=200, null=True, blank=True)
    job_poster = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE,
        related_name="posted_jobs")
    interested_member = models.ManyToManyField(
        UserProfile, blank=True)
    confirmed_member = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, null=True,
        blank=True, related_name="confirmed_jobs")
    job_title = models.CharField(null=True, max_length=150)
    image = models.ImageField(upload_to="job_images", null=True, blank=True)
    event_name = models.CharField(max_length=150)
    artist_name = models.CharField(max_length=100, null=True, blank=True)
    job_description = models.TextField(max_length=500)
    fee = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, default=0)
    event_city = models.CharField(max_length=100)
    event_country = CountryField()
    event_datetime = models.DateTimeField()
    interest_count = models.IntegerField(null=True, blank=True, default=0)
    is_taken = models.BooleanField(default=False)

    objects = JobManager()

    def __str__(self):
        """
        Return string representation of Job object.
        """
        return f"{self.job_poster}'s job: {self.event_name}"

    def generate_job_number(self):
        """
        Generate random UUID string to represent Job.
        """
        return uuid.uuid4().hex.upper()

    def save(self, *args, **kwargs):
        """
        Generate a Job number upon creation of a job object
        """
        if not self.job_number:
            self.job_number = self.generate_job_number()
        super().save(*args, **kwargs)

profiles/models.py
from django.db import models
from django.db.models import Max
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator
from django.utils.text import slugify

from django.urls import reverse


class Instrument(models.Model):
    """
    Instrument Model
    ------------------------

    Represents a list of individual Instrument choices.

    Used as a ManyToMany field, related to the UserProfile model.

    Attributes:

        instrument_name = Field representing the name of the instrument.
    """

    # Assigning first value in 'choices' tuple to avoid
    # errors and seperate logic.
    VOCALS = "Vocals"
    GUITAR = "Guitar"
    BASS_GUITAR = "Bass Guitar"
    KEYBOARD = "Keyboard"
    PIANO = "Piano"
    DRUMS = "Drums"
    PERC = "Percussion"
    TRUMPET = "Trumpet"
    TENOR_TROMB = "Tenor Trombone"
    BASS_TROMB = "Bass Trombone"
    SOUSAPHONE = "Sousaphone"
    TENOR_SAX = "Tenor Saxophone"
    ALTO_SAX = "Alto Saxphone"
    BARITONE_SAX = "Baritone Saxophone"
    FLUTE = "Flute"
    CLARINET = "Clarinet"
    ACCORDION = "Accordion"
    VIOLIN = "Violin"
    CELLO = "Cello"
    DOUBLE_BASS = "Double Bass"
    VIOLA = "Viola"
    VIBRAPHONE = "Vibraphone"
    HARMONICA = "Harmonica"

    # Define the choices available to the user when
    # selecting their instruments.
    # Passed as 'choices' argument in CharField.
    INSTRUMENTS = [
        (VOCALS, "vocals"),
        (GUITAR, "guitar"),
        (BASS_GUITAR, "bass guitar"),
        (KEYBOARD, "keyboard"),
        (PIANO, "piano"),
        (DRUMS, "drums"),
        (PERC, "percussion"),
        (TRUMPET, "trumpet"),
        (TENOR_TROMB, "tenor trombone"),
        (BASS_TROMB, "bass_trombone"),
        (SOUSAPHONE, "sousaphone"),
        (ALTO_SAX, "alto saxophone"),
        (TENOR_SAX, "tenor saxophone"),
        (BARITONE_SAX, "baritone saxophone"),
        (FLUTE, "flute"),
        (CLARINET, "clarinet"),
        (ACCORDION, "accordion"),
        (VIOLIN, "violin"),
        (VIOLA, "viola"),
        (CELLO, "cello"),
        (DOUBLE_BASS, "double bass"),
        (HARMONICA, "harmonica"),
        (VIBRAPHONE, "vibraphone")
    ]

    instrument_name = models.CharField(
        max_length=50, unique=True, choices=INSTRUMENTS,
        null=True, blank=True, default="All")

    def __str__(self):
        """
        Define string representation of instrument
        """
        return self.instrument_name


class Genre(models.Model):
    """
    Genre Model
    --------------------

    Represents a list of individual Genre choices.

    Used as a ManyToMany field, related to the UserProfile model.

    Attributes:

        genre_name = Field representing the name of the genre.
    """

    POP = "Pop"
    ROCK = "Rock"
    JAZZ = "Jazz"
    CLASSICAL = "Classical"
    FUNK = "Funk"
    SOUL = "Soul"
    RNB = "RnB"
    PUNK = "Punk"
    LATIN = "Latin"
    BOSSA_NOVA = "Bossa Nova"
    HIP_HOP = "Hip Hop"
    METAL = "Metal"
    PROG_ROCK = "Prog Rock"
    EXPERIMENTAL = "Experimental"
    AMBIENT = "Ambient"
    CLUB_MUSIC = "Club Music"
    HOUSE = "House"

    GENRES = [
        (POP, "pop"),
        (ROCK, "rock"),
        (JAZZ, "jazz"),
        (CLASSICAL, "classical"),
        (FUNK, "funk"),
        (SOUL, "soul"),
        (RNB, "rnb"),
        (PUNK, "punk"),
        (LATIN, "latin"),
        (BOSSA_NOVA, "bossa_nova"),
        (HIP_HOP, "hip_hop"),
        (METAL, "metal"),
        (PROG_ROCK, "prog_rock"),
        (EXPERIMENTAL, "experimental"),
        (AMBIENT, "ambient"),
        (CLUB_MUSIC, "club_music"),
        (HOUSE, "house")
    ]

    genre_name = models.CharField(max_length=50, choices=GENRES,
                                  null=True, blank=True, unique=True,
                                  default="All")

    def __str__(self):
        """
        Define string representation of genre.
        """
        return self.genre_name


class UserProfileQueryset(models.QuerySet):
    """
    User Profile Query Set to handle searching and filtering
    through URL query parameters, specified in the "Find a Dep"
    page.

    Methods:

        filter_by_params():
            Query the entire UserProfile object using filter
            params specified in "Find a Dep" page select
            elements and buttons.

            Users with 'is_paid' status get priority listing
            by default, regardless of sort params.
    """

    def filter_by_params(self, filter_params, date_today, sort_params):

        if date_today:
            return self.filter(
                **filter_params).exclude(unavailable_user__date=date_today)

        return self.filter(**filter_params).order_by(
            sort_params, "-is_paid").exclude(subscription_chosen=False)


class UserProfileManager(models.Manager):
    """
    Custom codex manager to handle Custom UserProfileQuerySet

    get_queryset():
        Preserve the original get_queryset method.

    filter_queryset():
        Calls the model's custom filter to query the model using filter
        params provided in Dep List and Job List pages,
        with optional 'date_today' and 'sort_params'

    """

    def get_queryset(self):

        return UserProfileQueryset(self.model, using=self._db)

    def filter_queryset(self, filter_params, date_today, sort_params):

        return (
            self.get_queryset().filter_by_params(
                filter_params, date_today, sort_params)
        )


class UserProfile(models.Model):
    """
    UserProfile Model
    ------------------------

    Represents a UserProfile instance.

    All fields are editable by the user excluding:

    - subscription_chosen
    - is_paid (Editable if they upgrade subscription of course)
    - invitation_count
    - slug

    Attributes:

    user - A OneToOne field with relation to AllAuth user account.

    first_name - User's First Name

    last_name - User's Last Name

    city - The city where the user resides.

    country - The country where the user resides.

    profile_image - An image field if user chooses to display profile image.

    instruments_played - A ManyToMany field providing user
                        with a choice list of instruments.

    genres - A ManyToMany field providing user with a choice list of genres.

    user_info - A large text field for users to provide their pitch
                and details.

    subscription_chosen - A Boolean representing if a user
                          has chosen a subscription.

    is_paid - A Boolean representing the user's subscription status.

    invitation_count - An incremental field representing
                       how many invites a user has received.

    slug - A slug representation of the user's username. Used as parameter in
           profile URL.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=60, null=True, blank=True)
    last_name = models.CharField(max_length=60, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    country = CountryField(blank_label="Country", null=True, blank=True)
    profile_image = models.ImageField(upload_to="uploads", null=True,
                                      blank=True)
    instruments_played = models.ManyToManyField(Instrument)
    genres = models.ManyToManyField(Genre)
    user_info = models.TextField(null=True, blank=True)
    subscription_chosen = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    invitation_count = models.IntegerField(
        default=0, null=True, blank=True, validators=[MinValueValidator(0)])
    average_rating = models.IntegerField(
        default=0, null=True, blank=True, validators=[MinValueValidator(0)])
    slug = models.SlugField(null=True, blank=True, db_index=True)

    # Instantiate custom UserProfileManager
    objects = UserProfileManager()

    def __str__(self):
        """
        Define the UserProfile model's string representation.
        """
        return self.user.username

    def save(self, *args, **kwargs):
        """
        Automatically create a slug from the user's
        username when a UserProfile object is created.
        """

        average_rating_object = self.calculate_average_rating
        if average_rating_object is not None:
            self.average_rating = average_rating_object["average_rating"]
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    @property
    def calculate_average_rating(self):
        """
        A property to calculate a user's average rating,
        to be displayed as stars on the User's profile
        and dashboard page, as well as the Dep List page.
        """
        received_reviews = self.received_reviews.all()
        if len(received_reviews) > 0:
            num_of_reviews = len(received_reviews)
            total_rating = 0
            for review in received_reviews:
                rating = review.rating
                if rating is not None:
                    total_rating += rating
                average_rating = round(total_rating/num_of_reviews)
            return {
                "average_rating": average_rating,
                "num_of_reviews": num_of_reviews
            }
        else:
            return None


class Equipment(models.Model):
    """
    Equipment Model
    -----------------

    Represents an individual item of Equipment which a user may declare.

    Attributes:

        equipment_name = Represents the name of the equipment item.
        related_user = A ManytoOne relationship with a given UserProfile.
    """

    class Meta:
        verbose_name_plural = "Equipment"

    equipment_name = models.CharField(max_length=300)
    related_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE,

jobs/templates/jobs/includes/filter_accordion.html
<!-- Filter Accordion shared by both dep_list.html and job_list.html, to search and filter querysets -->
<div class="container-fluid p-0">
            <div class="row m-0">
                <div class="col-12 p-0">
                    <div class="accordion rounded-0" id="filter_dep_accordion">
                        <div class="accordion-item border-0 rounded-0">
                            <h2 class="accordion-header rounded-0">
                                <button class="accordion-button dark_bg white_font med_small_text secondary_font rounded-0 shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#filter_collapse" aria-expanded="true" aria-controls="filter_collapse">
                                    Filter Your Results
                                </button>
                            </h2>
                        <div id="filter_collapse" class="accordion-collapse collapse show">
                            <div class="accordion-body {% if p == "job_list" %}job_list{% endif %} light_bg">
                                <div class="row m-0">
                                    {% if p == "dep_list" %}
                                    <div class="col-12">
                                        <div class="instrument_searchbar_select">
                                            <!-- Dep List Filter/Search Accordion -->
                                        <form action="{% url "dep_list" %}" method="GET" id="instrument_filter_form">
                                            <label for="instrument_filter" class="secondary_font mb-1">I'm Looking For...</label>
                                            <select class="form-select secondary_font" name="instrument" id="instrument_filter" aria-label="Instrument Filter">
                                                <option value="all">All</option>
                                                {% for instrument in instrument_list %}
                                                    <option value="{{ instrument.instrument_name }}" {% if selected_instrument == instrument.instrument_name|capfirst %}selected{% endif %}>{{instrument.instrument_name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <hr class="d-block d-md-none m-0">
                                <div class="row d-flex justify-content-center m-0 top_border">
                                    <div class="col-12 col-md-4 filter_field bottom_border" id="city_search_wrapper"> 
                                        <label for="city" class="secondary_font mb-1">Lives in this City:</label>       
                                        <input class="form-control secondary_font shadow-none" placeholder="Manchester, Glasgow..." type="text" name="city" value="{% if not city is empty %}{{ city }}{% endif %}" id="city">
                                        <span class="icon-inside"><i class="fas fa-search"></i></span>
                                    </div>
                                    <hr class="d-block d-md-none m-0">
                                    <div class="col-12 col-md-4 filter_field bottom_border">
                                        <label for="genre" class="secondary_font me-1 mb-1">Plays this Genre...</label>
                                        {% if genre_list %}
                                            <select class="form-select secondary_font" name="genre" id="genre">
                                                <option value="all">All Genres</option>
                                                {% for genre in genre_list %}
                                                    <option value="{{genre.genre_name}}" {% if selected_genre == genre.genre_name %}selected{% endif %}>{{genre.genre_name}}</option>
                                                {% endfor %}
                                            </select>
                                        {% endif %}
                                    </div>
                                    <hr class="d-block d-md-none m-0">
                                    <div class="col-12 col-md-4 centered filter_field bottom_border">
                                        <label for="available_today_checkbox" class="secondary_font">Available Today</label>
                                        <input type="checkbox" name="available_today" value="{% if not availabletoday_checkbox_selected is empty %}true{% else %}false{% endif %}" id="available_today_checkbox">
                                    </div>
                                    <div class="col-8 col-md-6 centered pt-3 pb-3 bottom_border">
                                        <div class="sort_select_wrapper">
                                            <label for="sort_select">&nbsp;</label>
                                            <select class="form-select float-start secondary_font sort_selector" name="sort" id="sort_select">
                                                <option value="reset" {% if sort == "reset" %}selected{% endif %}>Sort By Rating</option>
                                                <option value="average_rating_asc" {% if sort == "average_rating_asc" %}selected{% endif %}>Low to High</option>
                                                <option value="average_rating_desc"{% if sort == "average_rating_desc" %}selected{% endif %}>High to Low</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-4 col-md-6 pt-3 pb-3">
                                        <button type="submit" class="btn custom_success white_font secondary_font">Submit</button>      
                                    </div>
                                    </form>
                                    {% else %}      
                                    </div>
                                </div>
                                <div class="row m-0 top_border">
                                    <div class="col-12 col-md-6 filter_field bottom_border pe-3 ps-3" id="city_search_wrapper">        
                                        <form action="{% url "job_list" %}" method="GET" id="instrument_filter_form">
                                            <label for="city" class="secondary_font mb-1">Search by City:</label>
                                            <input class="form-control secondary_font shadow-none" placeholder="Search by City..." type="text" name="event_city" value="{% if not city is empty %}{{ city }}{% endif %}" id="city">
                                            <span class="icon-inside job_list"><i class="fas fa-search"></i></span>
                                    </div>
                                    <hr class="d-block d-md-none m-0">
                                    <div class="col-12 col-md-6 filter_field bottom_border pe-3 ps-3">
                                        <label for="fee_select" class="secondary_font me-1 mb-1">Select your Fee Range:</label>
                                                <select class="form-select secondary_font" name="fee" id="fee_select">
                                                    <option value="all">All Fee Ranges</option>
                                                        <option value="1-100" {% if selected_fee == "1-100" %}selected{% endif %}>£1 - £100</option>
                                                        <option value="101-200" {% if selected_fee == "101-200" %}selected{% endif %}>£101 - £200</option>
                                                        <option value="201-300" {% if selected_fee == "201-300" %}selected{% endif %}>£201 - £300{{genre.genre_name}}</option>
                                                        <option value="301-500" {% if selected_fee == "301-500" %}selected{% endif %}>£301 - £500</option>
                                                        <option value="500"{% if fee == "500" %}selected{% endif %}>£500+</option>
                                                </select>
                                            </div>
                                            <hr class="d-block d-md-none m-0">
                                            <div class="col-12 pt-3 pb-3 centered">
                                                <button type="submit" class="btn custom_success white_font secondary_font">Submit</button>   
                                            </div>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <hr class="d-block d-md-none m-0">
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

jobs/templates/jobs/includes/pagination.html
{% if p == "dep_list" %}
    <div id="pagination-wrapper" class="primary_bg">
        <div class="pagination centered">
            {% if page_obj.has_previous %}
                <span class="step-links">
                    <a href="{% url "dep_list" %}?{% append_page_no_to_url_params page=1 %}" class="secondary_font white_font">&laquo; first</a>
                    <a href="{% url "dep_list" %}?{% append_page_no_to_url_params page=page_obj.previous_page_number %}" class="secondary_font white_font">prev</a>
                {% endif %}
                    <span class="current secondary_font white_font page_no_indicator">
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}
                    </span>
                {% if page_obj.has_next %}
                    <span class="step-links">
                        <a href="{% url "dep_list" %}?{% append_page_no_to_url_params page=page_obj.next_page_number %}" class="secondary_font white_font">next</a>
                        <a href="{% url "dep_list" %}?{% append_page_no_to_url_params page=paginator.num_pages %}" class="secondary_font white_font">last &raquo;</a>
                    </span>
                </span>
            {% endif %}
        </div>
    </div>
{% else %}
    <div id="pagination-wrapper" class="primary_bg">
        <div class="pagination centered">
            {% if page_obj.has_previous %}
                <span class="step-links">
                    <a href="{% url "job_list" %}?{% append_page_no_to_url_params page=1 %}" class="secondary_font white_font">&laquo; first</a>
                    <a href="{% url "job_list" %}?{% append_page_no_to_url_params page=page_obj.previous_page_number %}" class="secondary_font white_font">prev</a>
                {% endif %}
                    <span class="current secondary_font white_font page_no_indicator">
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}
                    </span>
                {% if page_obj.has_next %}
                    <span class="step-links">
                        <a href="{% url "job_list" %}?{% append_page_no_to_url_params page=page_obj.next_page_number %}" class="secondary_font white_font">next</a>
                        <a href="{% url "job_list" %}?{% append_page_no_to_url_params page=paginator.num_pages %}" class="secondary_font white_font">last &raquo;</a>
                    </span>
                </span>
            {% endif %}
        </div>
    </div>
{% endif %}